<!-- Place this line to line #16 to attach the stylesheet
$this->headLink()->prependStylesheet($this->assetUrl('css/uofr-header.css'));  -->

<!-- Place the div at line #70 in layout.phtml -->
    <div class="header-top">
                <div class="university-logo">
                    <a href="https://rochester.edu/"><img alt="University of Rochester logo" src="https://www.rochester.edu/ohsp/wp-content/themes/ur-core/img/theme/branding-assets/ur-logo.svg"/></a>
                </div>    
                <div class="blue-navbar">
                    <a href="https://rochester.edu/libraries/" class="site-heading">University of Rochester Libraries</a>
                    <div class="exhibit-home">
                        <a href="https://urexhibits.lib.rochester.edu/s/Search/page/home">Digital Exhibits</a>
                    </div>
               </div>
    </div>
