<!-- Place this line to line #16 to attach the stylesheet
$this->headLink()->prependStylesheet($this->assetUrl('css/uofr-header.css'));  -->

<!-- Place the div at line #70 in layout.phtml -->
<div class="header-top">
                <a class="university-logo" href="https://rochester.edu/"><img alt="University of Rochester" src="https://www.facilities.rochester.edu/_assets/img/UR.2col.v1.rev.png" alt="The University of Rocheter Library logo"/></a>
                <a href="https://urexhibits.lib.rochester.edu/ "class="site-heading">University of Rochester Digital Exhibitions</a>
</div>